Update names for Polish neighbourhood
whosonfirst-data/whosonfirst-data-admin-pl pull request #43
Opened 2022-05-11 18:52 UTC by stepps00

This PR updates names for a neighbourhood in Poland. All existing names are stored as variants, and new preferred names have been added. No PIP work needed.

2022-05-11 20:29 UTC, nvkelso commented on data/149/500/582/3/1495005823.geojson
> +        "Go\u015bcicino"
This is the same as the Eng preferred, so the Eng variant should be dropped.

2022-05-11 20:29 UTC, nvkelso commented on data/149/500/582/3/1495005823.geojson
> +    "name:rus_x_variant":[
If it's the only one, then Rus preferred

2022-05-11 20:30 UTC, nvkelso requested changes
Nits

2022-05-12 16:59 UTC, stepps00 commented
Good catches.. I've updated the record to reflect these comments. The record should now be ready to merge.

2022-05-13 00:34 UTC, nvkelso commented on data/149/500/582/3/1495005823.geojson
> +    "wof:name":"Go\u015bcicino",
NIt: Is there an ASCII7 version?

2022-05-13 00:34 UTC, nvkelso approved these changes

2022-05-18 22:45 UTC, stepps00 commented on data/149/500/582/3/1495005823.geojson
> +    "wof:name":"Go\u015bcicino",
Updated in a more recent commit..

2022-05-18 23:01 UTC, nvkelso approved these changes

2022-05-19 23:21 UTC, merged